### ISSUE TITLE
Import circular dependency error regarding restart module

### ISSUE THREAD

**Issue by armantekinalp** [SophT-Team/SophT#162]
Hi @ilianasiriziba 

Can you take care this issue? There is an import error in sopht due to the restart module import. It is giving an error saying there are circular dependencies.

@sy-cui  suggested a quick fix is to `import sopht.utils ` then `import sopht.simulator`

Here is the ss of error

<img width="1630" alt="Screen Shot 2023-09-26 at 4 55 50 PM" src="https://github.com/SophT-Team/SophT/assets/53585636/849b1a27-bada-4908-b87d-cdfc2ee3deaf">

**Comment by ilianasiriziba** [comment]
Hi @armantekinalp 

In the latest version of the restart example, I fixed the order for imports. If you check that it imports utils first. I also run the example again and it is working fine.

**Comment by sy-cui** [comment]
Hi @ilianasiriziba .

You are right. At the moment most case files should be working. However, a simple way to recreate the issue is to have a new file with the following lines
```py
import sopht.simulator as sps
import sopht.utils as spu
```
This will cause a circular import error because `spu` is imported within some `sps` files, while restart_sim also imports some of the `sps` objects. 

I think a easy fix is to remove all references to flow simulator related types (or anything related to `sps` for that matter) within `restart_sim.py`, and return the current time from the function
```py
def restart_simulation(
    # No flow_sim here
    ...
):
    ...
    curr_time = io.load(...)
    ...
    return curr_time
```
then in case files (`restart_example.py`, for example) correct the flow simulator time
```py
time = restart_simulation(...)
flow_sim.time = time
```
This avoid import `sps` members inside an `spu` file. @ilianasiriziba do you want to try this an confirm if it works?

**Comment by ilianasiriziba** [comment]
Hi @sy-cui 

Sure, I'll try this and let you know.
